### ISSUE TITLE
Empty registry page

### ISSUE THREAD

**Issue by junelsolis** [BioContainers/registry#116]
Browsing to [biocontainers.pro/registry](https://biocontainers.pro/registry) shows an empty page with a spinner. After several seconds, the browser console shows the following error:
![image](https://user-images.githubusercontent.com/11444749/133126856-bdc8c2d3-fcb7-436e-a3e6-d04a33726601.png)

**Comment by neoformit** [comment]
I am also getting inconsistent errors at `/registry`. It errorred twice and worked once. 

### Console output:
![image](https://user-images.githubusercontent.com/42562517/135538172-8b02ea42-4531-40ac-baff-2159970780da.png)

---

### Console log:
[biocontainers.pro-1633040680754.log](https://github.com/BioContainers/registry/files/7262853/biocontainers.pro-1633040680754.log)

---

### Browser view:
![image](https://user-images.githubusercontent.com/42562517/135538309-a4619959-4451-43a1-98e3-a184b9ff1b92.png)

**Comment by osallou** [comment]
Hi,
Just did a test and worked.
Are you still facing the issue?

**Comment by junelsolis** [comment]
Hello, thanks for the update. It kind of works...

It takes almost 1 minute with the "pulsing dot" spinner, until the empty list shows up saying "No Data". But there is a pagination control at the bottom. 🤷🏼‍♂️ 
![image](https://user-images.githubusercontent.com/11444749/135672642-c798d04a-6b9c-49b6-af47-f1428032f49b.png)

If I type a search query, then a list of results shows up:
![image](https://user-images.githubusercontent.com/11444749/135672940-a693cdc1-c17d-4afa-b7f0-4268274e973e.png)

If I then emtpy the search query, then now it shows the containers in alphabetical order. 

- Is the default behavior supposed to be that the registry search page shows all the containers by default?
- There are several console messages being output by Vue. Shouldn't this be hidden in a production environment?

**Comment by osallou** [comment]
Regading vuejs, yes *should* not appear, but not a big deal ;-) nothing private.
I suppose app is somehow in dev mide vs prod mode.

Regarding listing of containers, we had other reports indeed, though when i tested it was fine.
Display is a bit long, because it seems that all data are loaded instead of using full pagination mechanisms. So time for display will depend on your bandwith. This should be enhanced however for quicker results.

**Comment by osallou** [comment]
The search/list behavior is not linked. Async requests are done, and main request toon long time to end. While your were on search, first request finished, and this explains you finally got the results.
You just did not wait long enough.

But as i said, this should be reworked as such long time to get data is not a good user experience...

**Comment by pveber** [comment]
For me (under Firefox/Linux and chromium), the search form remains grayed and blank, even after several hours. The browser log says there's a blocked cross-origin request.

**Comment by osallou** [comment]
yeap could reproduce today, seems to work "sometimes" but here facets request on containers failed
@ypriverol can you look at registry web issues?

though always quite long, I created an issue to fix such delay....
