### ISSUE TITLE
Blank pages on web UI?

### ISSUE THREAD

**Issue by schorlton** [BioContainers/registry#125]
Currently been getting blank templates via the web UI (for any biocontainer) for a couple days so figured would report. Is there any way to figure out the tag of a container without the web UI? Thanks for your amazing work!

![image](https://user-images.githubusercontent.com/10245822/153723815-14d6e2d4-67aa-400d-a8b0-aeaa77873e46.png)

**Comment by osallou** [comment]
Hi, 
Thanks for reporting

you can still get the available tags on dockerhub or quay.io related page (depending on container)

**Comment by osallou** [comment]
Look like could issues

* kubernetes is very very slow
* mongodb looks in brokebn state, a restart fails to attach cinder volume
* api restarted (but mongo being down...)
* can't even login to ebi cloud

**Comment by fabianegli** [comment]
I still get the empty page as screenshotted by OP. e.g. for https://biocontainers.pro/tools/fastqc
![Screenshot](https://user-images.githubusercontent.com/8569110/157107445-30faac52-82fa-4f68-b029-9c550b844ca2.png)
