### ISSUE TITLE
Recent versions of Bioconda based tool containers not available

### ISSUE THREAD

**Issue by oschwengers** [BioContainers/registry#142]
Hi, I just recognized that for Bakta, none of the recent software versions are included in [biocontainers](https://biocontainers.pro/tools/bakta).
However, the Bioconda-based software containers are available on [quay.io](https://quay.io/repository/biocontainers/bakta), so this must be somehow related to Biocontainers itself.

I cant tell whether this is related only to Bakta or if this is maybe a general issue.

**Comment by osallou** [comment]
Hi,
Registry should be updated every week, so seems there is indeed an issue in update process

Thanks for info.

**Comment by osallou** [comment]
@ypriverol @chakrabandla ?

**Comment by ypriverol** [comment]
I will double check.

**Comment by osallou** [comment]
@ypriverol @chakrabandla did you check registry status/update?

**Comment by osallou** [comment]
found an issue in pipeline, seems quay.io changed api some time ago, and now, pipeline fetch first page only of repositories. Pipeline need to be modified to fetch all pages using next_page element of api

**Comment by osallou** [comment]
forced launch of a new scan after fixing the pipeline and use quay.io API pagination

**Comment by osallou** [comment]
build in progress and mmannot is now here (partial data for the moment, whole job not over), waiting for the end of search/index pipeline to close issue

**Comment by osallou** [comment]
@mzytnicki 

https://api.biocontainers.pro/ga4gh/trs/v2/tools/mmannot/versions/mmannot-1.0.3  is ok now

**Comment by osallou** [comment]
@oschwengers bakta is visible now

**Comment by oschwengers** [comment]
Thanks a lot. Cheers!
