### ISSUE TITLE
Better deployment in github-pages 

### ISSUE THREAD

**Issue by ypriverol** [BioContainers/registry#40]
We need to implement a mechanism that everytime we accept a PR in Master, the web get deploy in github-pages and can be seen in registry.github.io. For that probalby we will need to rename the repository as registry. 

We should use travis for this deployment.

**Comment by bgruening** [comment]
@ypriverol travis has been bought and the future does not look bright. You might look at CirceCI or Azure Pipelines for this.

**Comment by ypriverol** [comment]
Thanks @bgruening the idea is not only to use travis is also to move into a workflow like: 

contribution to -> master -> merge PR -> CI push to GH-pages -> Web updated. 

This was not the case before but now is there. We can replace Travis in the future with our jenkins.

**Comment by ypriverol** [comment]
Done
