### ISSUE TITLE
Non-safe link behind Quick-start button

### ISSUE THREAD

**Issue by kjellp** [BioContainers/registry#70]
There seem to be an issue with the Quick-start link/button on the front page. Browsers warn about unsafe link. The documentation menu item is working without this problem, effectively bringing the user to the same content on readthedocs.io.

**Comment by osallou** [comment]
I think cause is the certificate is not a wildcard one, and is using an other certificate.
@ypriverol, you need to set a specific cert for this site or use a wildcard one

**Comment by ypriverol** [comment]
This has been fixed in the current version of the web.
