### ISSUE TITLE
Change sorting order of containers bt "Pull no"

### ISSUE THREAD

**Issue by jeanmanguy** [BioContainers/registry#75]
Currently sorting containers using "Pulls no" sort containers by ascending order showing the newest or least popular containers first. 

I suggest to change the sorting order or to add a third sorting options with "ascending" and "descending" options

**Comment by ypriverol** [comment]
We have fix this issue. Sorry for the delay.

**Comment by jeanmanguy** [comment]
Thank you

**Comment by ypriverol** [comment]
More than welcome, if you would like to see more features in the Web just let us know !!!!
