### ISSUE TITLE
Server Error in registry

### ISSUE THREAD

**Issue by aliceminotto** [BioContainers/registry#76]
Hi all,

I hope this is a good place to report this. The biocontainers registry has been returning Server Error for about a week and doesn't return anything for any search.

**Comment by osallou** [comment]
Hi,
yeap, our hosting infra was in a maintenance/move operation, expected to last some time (don't know how long), but with the covid virus, I suppose it will take much more time to make their cloud up again....
In the meanwhile, all hosted virtual machines for CI, internal registry etc... are unfortunatly down and unavailable.

**Comment by ypriverol** [comment]
Problem solve

**Comment by fabianegli** [comment]
The same issue seems to have reestablished itself.
